### ISSUE TITLE
Data not available

### ISSUE THREAD

**Issue by nabeelkhalid92** [pkainz/MICCAI2015#4]
Dear,

First of all thank you for your amazing work.

Unfortunately, the data is not available on the given link.

Can you please update the link or upload the data somewhere else and share the link.

Thank you and kind regards,
Nabeel Khalid

**Comment by pkainz** [comment]
Hi @nabeelkhalid92,
Fhanks for letting me know. The data download link has been updated. You can [download the dataset as ZIP here](https://github.com/pkainz/MICCAI2015/raw/master/BM_dataset_MICCAI2015.zip)
